### ISSUE TITLE
Error when upgrading to selenium 2.49.0

### ISSUE THREAD

**Issue by rserrano** [baijum/selenium-python#58]
Hi, good day.

I upgraded selenium python yesterday to 2.49.0 and this error started appearing. Not in every test, but on 5 of about 20. Downgrading to 2.48.0 solved the problem. Thanks.

Traceback (most recent call last):
  File "xxxx/yyy/tests/test_frontend_simple.py", line 871, in test_add_study
    submit.click()
  File "xxxx/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 75, in click
    self._execute(Command.CLICK_ELEMENT)
  File "xxxx/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 454, in _execute
    return self._parent.execute(command, params)
  File "xxxx/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "xxxx/env/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 102, in check_response
    value = json.loads(value_json)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by rserrano** [comment]
Sorry, I thought this was the page for the python - selenium bindings. It seems as an only Python bug, but I will publish it in selenium. Thanks.
